global using BoDi;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Playwright;
global using NUnit.Framework;
global using PlaywrightPracticeTask2024.Config;
global using PlaywrightPracticeTask2024.Drivers;
global using PlaywrightPracticeTask2024.Models;
global using PlaywrightPracticeTask2024.Pages;
global using System.Runtime.Serialization;
global using TechTalk.SpecFlow;
global using TechTalk.SpecFlow.Assist;
global using static PlaywrightPracticeTask2024.Enums.Keywords;
global using NUnit.Framework;